### ISSUE TITLE
Adding queries to form

### ISSUE THREAD

**Issue by sabagsapir** [orbardugo/Hahot-Hameshulash#36]
#### Tasks
- [x] מס' מוסדות - טווח מספרי
- [x] רצף זנות - רשימה נגללת 
- [x] רצף קורת גג - רשימה נגללת
